export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CYCLING_DATA_REQUEST = 'CYCLING_DATA_REQUEST';
export const CYCLING_DATA_SUCCESS = 'CYCLING_DATA_SUCCESS';
export const CYCLING_DATA_FAILURE = 'CYCLING_DATA_FAILURE';

export const RUNNING_DATA_REQUEST = 'RUNNING_DATA_REQUEST';
export const RUNNING_DATA_SUCCESS = 'RUNNING_DATA_SUCCESS';
export const RUNNING_DATA_FAILURE = 'RUNNING_DATA_FAILURE';
